### ISSUE TITLE
"The server isn't offline or online"

### ISSUE THREAD

**Issue by Pexien** [Vrganj/Minehut#1]
Found this by accident when trying out the web panel
![Screenshot 2019-07-04 at 12 23 43 AM](https://user-images.githubusercontent.com/22846138/60639809-2c285d00-9df2-11e9-9ffa-bb404b2e2fb3.png)

**Comment by Vrganj** [comment]
What's the problem, though?

**Comment by Pexien** [comment]
it says "the sever isn't online or offline", in a perfect world it would either say "online, "offline", or "idle/starting"
